"""slice 0 initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 14:31:39.706931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_type_registry',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('claim_class', sa.String(), nullable=False),
    sa.Column('subject_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('natural_key', sa.Text(), nullable=True),
    sa.Column('volatility', sa.String(), nullable=True),
    sa.Column('default_review', sa.String(), nullable=True),
    sa.Column('payload_schema', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('flag_type_registry',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('default_severity', sa.String(), nullable=False),
    sa.Column('brief_template', sa.Text(), nullable=True),
    sa.Column('blocks_auto_approval', sa.Boolean(), nullable=False),
    sa.Column('blocks_matching', sa.Boolean(), nullable=False),
    sa.Column('valid_subject_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('org',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('source_authority', sa.String(), nullable=False),
    sa.Column('transformed_by_third_party', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('as_of_basis', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('needs_vision', sa.Boolean(), nullable=False),
    sa.Column('last_processed_with', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('cv', 'jd', 'other')", name='document_doc_type'),
    sa.CheckConstraint("source_authority IN ('verified_primary', 'human_assertion', 'candidate_authored', 'employer_authored', 'third_party_assertion', 'web_inference')", name='document_authority'),
    sa.CheckConstraint("status IN ('received', 'stored', 'extracted', 'processed', 'needs_human', 'reprocessable')", name='document_status'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'sha256')
    )
    op.create_table('document_subject',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('segment_locator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('established_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'subject_type', 'subject_id')
    )
    op.create_table('extraction_artifact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('annotations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_sha', sa.String(length=64), nullable=False),
    sa.Column('produced_with', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('text_layer', 'vision')", name='artifact_method'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intelligence_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('version_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'committed', 'failed')", name='run_status'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('hiring_company', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('open', 'on_hold', 'filled', 'cancelled')", name='job_state'),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('not_same',
    sa.Column('candidate_a', sa.UUID(), nullable=False),
    sa.Column('candidate_b', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('candidate_a < candidate_b', name='not_same_ordered'),
    sa.ForeignKeyConstraint(['candidate_a'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['candidate_b'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('candidate_a', 'candidate_b')
    )
    op.create_table('candidate_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('triage_band', sa.String(), nullable=False),
    sa.Column('triage_reason', sa.String(), nullable=True),
    sa.Column('band_overridden_by', sa.String(), nullable=True),
    sa.Column('pair_state', sa.String(), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("triage_band IN ('priority', 'review_later', 'do_not_submit', 'unassigned')", name='pair_band'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['candidate_job.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id')
    )
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('class', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('natural_key', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('temporal_precision', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verifiability', sa.String(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approved_view', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_view_hash', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('observed_as_of', sa.Date(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("class IN ('observed', 'inferred', 'computed')", name='claim_class'),
    sa.CheckConstraint("status IN ('staged', 'proposed', 'approved', 'rejected', 'superseded')", name='claim_status'),
    sa.CheckConstraint("subject_type IN ('candidate', 'company', 'job')", name='claim_subject_type'),
    sa.CheckConstraint("temporal_precision IN ('exact', 'month', 'year_only', 'ordered_only', 'unknown')", name='claim_precision'),
    sa.ForeignKeyConstraint(['claim_type'], ['claim_type_registry.key'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['intelligence_run.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['claim.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_natural_key', 'claim', ['org_id', 'claim_type', 'natural_key'], unique=False)
    op.create_index('ix_claim_subject', 'claim', ['org_id', 'subject_type', 'subject_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('revision_diff', 'duplicate_stint', 'contradiction', 'identity_note')", name='decision_type'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('span_validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_authority', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('observed_as_of', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('candidate', 'employer', 'registry', 'independent_web', 'human', 'relayed', 'unknown')", name='evidence_origin'),
    sa.CheckConstraint("source_authority IN ('verified_primary', 'human_assertion', 'candidate_authored', 'employer_authored', 'third_party_assertion', 'web_inference')", name='evidence_authority'),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_observation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('attribute_path', sa.String(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('source_authority', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('observed_as_of', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origin IN ('candidate', 'employer', 'registry', 'independent_web', 'human', 'relayed', 'unknown')", name='obs_origin'),
    sa.CheckConstraint("source_authority IN ('verified_primary', 'human_assertion', 'candidate_authored', 'employer_authored', 'third_party_assertion', 'web_inference')", name='obs_authority'),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_observation')
    op.drop_table('evidence')
    op.drop_table('decision_item')
    op.drop_table('decision')
    op.drop_index('ix_claim_subject', table_name='claim')
    op.drop_index('ix_claim_natural_key', table_name='claim')
    op.drop_table('claim')
    op.drop_table('candidate_job')
    op.drop_table('not_same')
    op.drop_table('job')
    op.drop_table('intelligence_run')
    op.drop_table('extraction_artifact')
    op.drop_table('document_subject')
    op.drop_table('document')
    op.drop_table('candidate')
    op.drop_table('org')
    op.drop_table('flag_type_registry')
    op.drop_table('claim_type_registry')
    # ### end Alembic commands ###
