"""pair events

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 23:08:50.848456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pair_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('pair_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('from_value', sa.String(), nullable=True),
    sa.Column('to_value', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('cause', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['pair_id'], ['candidate_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pair_event_pair', 'pair_event', ['pair_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pair_event_pair', table_name='pair_event')
    op.drop_table('pair_event')
    # ### end Alembic commands ###
