"""pair event order

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-02 23:17:21.291349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pair_event', sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.create_unique_constraint('uq_pair_event_seq', 'pair_event', ['seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_pair_event_seq', 'pair_event', type_='unique')
    op.drop_column('pair_event', 'seq')
    # ### end Alembic commands ###
