"""companies

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-03 17:54:53.480767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('registry_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized')
    )
    op.create_table('company_alias',
    sa.Column('normalized', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('normalized')
    )
    op.add_column('job', sa.Column('hiring_company_id', sa.UUID(), nullable=True))
    op.drop_constraint("decision_type", "decision", type_="check")
    op.create_check_constraint("decision_type", "decision",
                               "type IN ('revision_diff', 'duplicate_stint', 'contradiction', 'identity_note', 'company_same')")
    op.create_foreign_key('job_hiring_company_id_fkey', 'job', 'company', ['hiring_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM decision_item WHERE decision_id IN (SELECT id FROM decision WHERE type = 'company_same')")
    op.execute("DELETE FROM decision WHERE type = 'company_same'")
    op.drop_constraint("decision_type", "decision", type_="check")
    op.create_check_constraint("decision_type", "decision",
                               "type IN ('revision_diff', 'duplicate_stint', 'contradiction', 'identity_note')")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('job_hiring_company_id_fkey', 'job', type_='foreignkey')
    op.drop_column('job', 'hiring_company_id')
    op.drop_table('company_alias')
    op.drop_table('company')
    # ### end Alembic commands ###
