"""company research

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-03 19:20:38.403235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('research_status', sa.String(), nullable=True))
    op.add_column('company', sa.Column('researched_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("INSERT INTO org (id, name) VALUES ('00000000-0000-0000-0000-00000000c0de', 'Public company knowledge') ON CONFLICT (id) DO NOTHING")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'researched_at')
    op.drop_column('company', 'research_status')
    # ### end Alembic commands ###
